# This is the name of workflow
name: Package Image Creation
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
# Jobs are listed to be run of GitHub runners-111. 
jobs:
    # This job is to validate all the input values used in workflow.
    Validate-Inputs:
      if: ${{contains(vars.job_switches, 'validate') }} 
      name: Pre Validation- Validate Inputs
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script using  repo variable
          run: packer validate -syntax-only .
          
      # This job is to setup and run packer to create managed image.       
    Setup-Run-Packer:
      if: ${{contains(vars.job_switches, 'packer') }} 
      needs: Validate-Inputs
      name: Image Build- Setup and run packer
      runs-on: ubuntu-latest
      environment: CSG_CRED
      steps:
        - uses: actions/checkout@v1
        - name: Set up Azure CLI
          uses: azure/login@v1
          with:
             creds: ${{ secrets.CSG_CRED }}
  
        - name: Build Azure Image
          env:
           CLIENT_ID: ${{ secrets.clientId }}
           CLIENT_SECRET: ${{ secrets.clientSecret }}
           SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
           TENANT_ID: ${{ secrets.tenantId }}
           
          run: >
            packer plugins install github.com/hashicorp/azure v2.0.1
            packer build -var 'clientId'="${CLIENT_ID}" -var 'clientSecret'="${CLIENT_SECRET}" -var 'subscriptionId'="${SUBSCRIPTION_ID}" -var 'tenantId'="${TENANT_ID}" 
    
    # This job is to do post validation on the image created as part of packer.  
    Post-Validation:
      if: ${{contains(vars.job_switches, 'postvalidation') }} 
      needs: Setup-Run-Packer
      name: Post Validation- Validate Image
      runs-on: ubuntu-latest
      
      steps:
        - name: Testing Image Validation Script
          run: |
           echo "Image Validation Script on environment"

    # This job is to publish the image in the Azure compute gallery.  
    Publish-image:
      if: ${{contains(vars.job_switches, 'skip') }} 
      needs:
      - Post-Validation
      name: Publish Image
      runs-on: ubuntu-latest
      environment: development
      steps:
        - name: Testing Image Publish Script
          run: |
           echo "Image Publish Script on environment : $env_var"
    
     
   



