---
name: Packer_image_creation
on:
  push: null
jobs:
  build:
    runs-on: self-hosted
    environment: AZURE
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Install Azure cli
        run: >
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release
          gnupg

          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

          AZ_REPO=$(lsb_release -cs)

          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

          sudo apt-get update

          sudo apt-get install azure-cli   
      - run: az --version
      
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE }}
      
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "testkeyvaults"
          secrets: 'clientid, clientsecret, subscriptionid, tenantid'
        id: myGetSecretAction

      - name: Packer Image
        run: |
          packer plugins install github.com/hashicorp/azure
          packer build -var-file="variables.pkrvars.hcl" VariablewithImage.pkr.hcl

        

    
     

           
